kind: Deployment
apiVersion: apps/v1
metadata:
  name: nodejs-app1
  namespace: default
  labels:
    app: nodejs-app1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs-app1
  template:
    metadata:
      labels:
        app: nodejs-app1
    spec:
      containers:
      - name: nodejs-app1
        image: 19931/mo60
        ports:
          - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: nodejs-app1
  labels:
    name: nodejs-app1
spec:
  type: NodePort
  ports:
    - port: 8080
      nodePort: 30000
      name: http
  selector:
    name: nodejs-app1
